server:
  port: 8080
spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
---
# Профиль для development
spring:
  config:
    activate:
      on-profile: development

  datasource:
    url: jdbc:h2:mem:test
    username: root
    password: root

---
# Профиль для test
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:test
    username: root
    password: root

---
# Профиль для production
spring:
  config:
    activate:
      on-profile: production

  datasource:
    url: jdbc:h2:mem:test
    username: root
    password: root
